from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import google.generativeai as genai
import requests
import xml.etree.ElementTree as ET
import os
import re
import json
import traceback

app = FastAPI()

# Vercel(프론트엔드)과의 통신을 위한 CORS 설정
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Gemini API 인증
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

model = genai.GenerativeModel('gemini-1.5-flash')

def extract_video_id(url: str):
    """유튜브 URL에서 11자리 고유 영상 ID를 추출"""
    match = re.search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url)
    return match.group(1) if match else None

# 🚨 [최종 완결판] 분산형 오픈소스 네트워크(Piped API) 기반 우회 엔진
# 유튜브의 로그인/봇 차단(CAPTCHA) 방화벽을 우회하기 위해 전 세계 Piped 노드를 활용합니다.
def fetch_transcript_decentralized(video_id: str):
    # 전 세계에 구축된 Piped 오픈소스 우회 노드 리스트
    instances = [
        "https://pipedapi.kavin.rocks",
        "https://pipedapi.adminforge.de",
        "https://api.piped.projectsegfau.lt",
        "https://pipedapi.smarthome-bielefeld.de"
    ]
    
    for instance in instances:
        try:
            print(f"🌐 분산형 노드 우회 시도 중: {instance}")
            # 우회 노드에 영상 데이터 요청
            res = requests.get(f"{instance}/streams/{video_id}", timeout=10)
            if res.status_code != 200:
                continue
            
            data = res.json()
            subtitles = data.get('subtitles', [])
            if not subtitles:
                continue
            
            # 우선순위: 영어(수동) -> 영어(자동) -> 한국어 -> 첫 번째 자막
            target = next((s for s in subtitles if s.get('code') == 'en' and not s.get('autoGenerated')), None)
            if not target: target = next((s for s in subtitles if s.get('code') == 'en'), None)
            if not target: target = next((s for s in subtitles if s.get('code') == 'ko'), None)
            if not target: target = subtitles[0]
                
            sub_url = target.get('url')
            if not sub_url:
                continue
                
            print(f"✅ 자막 URL 확보 성공 ({instance}). 익명 다운로드 진행 중...")
            sub_res = requests.get(sub_url, timeout=10)
            sub_text = sub_res.text
            
            parsed_data = []
            
            # 1. XML 포맷 파싱
            if sub_text.strip().startswith('<?xml') or sub_text.strip().startswith('<transcript'):
                root = ET.fromstring(sub_text)
                for child in root:
                    if child.tag == 'text':
                        start = float(child.attrib.get('start', 0))
                        text_content = child.text
                        if text_content:
                            text_content = text_content.replace('&amp;', '&').replace('&#39;', "'").replace('&quot;', '"')
                            parsed_data.append({'start': start, 'text': text_content})
            
            # 2. JSON3 포맷 파싱 (유튜브 기본)
            elif sub_text.strip().startswith('{'):
                json_data = json.loads(sub_text)
                for event in json_data.get('events', []):
                    if 'segs' in event:
                        text_content = "".join([seg.get('utf8', '') for seg in event['segs']]).replace('\n', ' ').strip()
                        if text_content:
                            parsed_data.append({
                                'start': event.get('tStartMs', 0) / 1000.0,
                                'text': text_content
                            })
                            
            # 3. WebVTT 포맷 파싱
            elif "WEBVTT" in sub_text:
                blocks = sub_text.split('\n\n')
                for block in blocks:
                    lines = block.split('\n')
                    if len(lines) >= 2 and '-->' in lines[0]:
                        time_str = lines[0].split('-->')[0].strip()
                        parts = time_str.split(':')
                        if len(parts) == 3:
                            start = float(parts[0])*3600 + float(parts[1])*60 + float(parts[2])
                            text = " ".join(lines[1:]).strip()
                            if text: parsed_data.append({'start': start, 'text': text})
                            
            if parsed_data:
                return parsed_data
                
        except Exception as e:
            print(f"⚠️ 노드 연결 실패 ({instance}): {e}")
            continue
            
    raise Exception("모든 글로벌 우회 노드가 유튜브 방화벽에 의해 차단되었습니다.")

@app.get("/")
def health_check():
    return {"status": "ok", "message": "분산형 프록시(Decentralized Proxy) 기반 엔진 실행 중!"}

@app.get("/api/analyze")
def analyze_youtube_video(video_url: str):
    video_id = extract_video_id(video_url)
    if not video_id:
        raise HTTPException(status_code=400, detail="유효하지 않은 유튜브 URL입니다.")

    # 1. 분산 네트워크를 통한 자막 우회 추출
    try:
        data = fetch_transcript_decentralized(video_id)
        full_text = " ".join([t['text'] for t in data])
        print(f"✅ 자막 추출 완벽 성공! 전체 길이: {len(full_text)}")
    except Exception as e:
        print(f"❌ 자막 추출 에러: {e}")
        raise HTTPException(status_code=400, detail=f"자막 추출 실패: {str(e)}")

    # 2. AI 분석 (요구사항: 정확히 '한 문장씩' 1:1 매칭 번역)
    try:
        print("Gemini AI로 한 문장씩 번역 요청 중...")
        prompt = f"""
        당신은 최고의 영어 학습 선생님입니다.
        제공된 유튜브 스크립트를 **정확히 한 문장씩(Sentence by sentence)** 나누어서 영어 원문과 한국어 번역을 1:1로 완벽하게 매칭해주세요.
        문장이 아닌 구문이 섞여 있더라도, 학습자가 읽기 편한 하나의 문장 단위로 합치거나 다듬어주세요.
        그리고 전체 내용에서 학습하기 좋은 핵심 영단어 5개를 뽑아주세요.

        반드시 아래 JSON 형식으로만 응답하세요:
        {{
            "script": [
                {{"text": "First English sentence.", "translation": "첫 번째 한국어 번역."}},
                {{"text": "Second English sentence.", "translation": "두 번째 한국어 번역."}}
            ],
            "vocab": [
                {{"word": "단어", "meaning": "뜻"}}
            ]
        }}

        스크립트: {full_text[:8000]}
        """
        response = model.generate_content(prompt)
        response_text = response.text.strip()
        
        # JSON 파싱 안정화
        if response_text.startswith("```json"):
            response_text = response_text[7:-3].strip()
        elif response_text.startswith("```"):
            response_text = response_text[3:-3].strip()

        ai_result = json.loads(response_text)

        # 3. 타임스탬프 (시작 시간) 매칭
        chunk_size = max(1, len(data) // max(1, len(ai_result.get('script', [1]))))
        for i, item in enumerate(ai_result.get('script', [])):
            idx = min(i * chunk_size, len(data) - 1)
            item['start'] = data[idx]['start']
            item['id'] = i + 1
            item['speaker'] = "Speaker"

        print("✅ AI 번역 및 데이터 처리 성공!")
        return ai_result

    except Exception as e:
        print(f"❌ AI 분석 에러:\n{traceback.format_exc()}")
        raise HTTPException(status_code=500, detail=f"AI 번역 실패: {str(e)}")
